### PR TITLE
Fix global css + few methods

### PR DESCRIPTION
**Pull request by TheoAt**

### CODE REVIEW

**Review by Tibo-Wild — CHANGES_REQUESTED** [review]
Repeating ServiceList and FormEvent to fix in App.js, and it might not be worth putting such a high number (999) for the z-index in Navbar.css

**Review by Tibo-Wild — APPROVED** [review]
Read and approved

**Review by Tibo-Wild — APPROVED** [review]
Read and approved

**Review by Tibo-Wild — APPROVED** [review]
Read and approved

**Review by Tibo-Wild — APPROVED** [review]
Read and approved

**Review by Tibo-Wild — APPROVED** [review]
Read and approved

**Review by ldupas — APPROVED** [review]

**Pull request merged**
